FROM public.ecr.aws/lambda/provided:al2023

COPY target/template-service ${LAMBDA_RUNTIME_DIR}/bootstrap
COPY src/main/resources/application-lambda.yml ${LAMBDA_TASK_ROOT}/config/application.yml

ENV SPRING_PROFILES_ACTIVE=lambda
ENV SPRING_MAIN_WEB-APPLICATION-TYPE=none
ENV LAMBDA_TASK_ROOT=/var/task
ENV LAMBDA_RUNTIME_DIR=/var/runtime

ENTRYPOINT [ "/var/runtime/bootstrap" ] 