version: '3.9'

services:
  db-mysql:
    container_name: db-mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: db
    volumes:
      - ~/data/mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    

  db-postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASS: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ~/data/postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432

      
  template:
    container_name: template
    depends_on:
      - db-mysql    
    image:  docker.io/egripp/spring3-native-template/template-service:1.0.0
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - 9090:9090


volumes:
  mysql-data:
  postgres-data:

  