spring:
  main:
    web-application-type: none
    allow-bean-definition-overriding: true
  cloud:
    function:
      definition: function
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/db
    username: root
    password: example
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        cache:
          use_second_level_cache: false
          use_query_cache: false
          region.factory_class: org.hibernate.cache.internal.NoCachingRegionFactory
        generate_statistics: false
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

eureka:
  client:
    enabled: false 